<?php

$timezones = [
	'Africa/Abidjan' => ['utc' => '+00:00', 'title_ru' => 'Африка/Абиджан'],
	'Africa/Accra' => ['utc' => '+00:00', 'title_ru' => 'Африка/Аккра'],
	'Africa/Addis_Ababa' => ['utc' => '+03:00', 'title_ru' => 'Африка/Аддис-Абеба'],
	'Africa/Algiers' => ['utc' => '+01:00', 'title_ru' => 'Африка/Алжир'],
	'Africa/Asmara' => ['utc' => '+03:00', 'title_ru' => 'Африка/Асмэра'],
	'Africa/Bamako' => ['utc' => '+00:00', 'title_ru' => 'Африка/Бамако'],
	'Africa/Bangui' => ['utc' => '+01:00', 'title_ru' => 'Африка/Банги'],
	'Africa/Banjul' => ['utc' => '+00:00', 'title_ru' => 'Африка/Банжул'],
	'Africa/Bissau' => ['utc' => '+00:00', 'title_ru' => 'Африка/Бисау'],
	'Africa/Blantyre' => ['utc' => '+02:00', 'title_ru' => 'Африка/Blantyre'],
	'Africa/Brazzaville' => ['utc' => '+01:00', 'title_ru' => 'Африка/Браззавиль'],
	'Africa/Bujumbura' => ['utc' => '+02:00', 'title_ru' => 'Африка/Бужумбура'],
	'Africa/Cairo' => ['utc' => '+02:00', 'title_ru' => 'Африка/Каир'],
	'Africa/Casablanca' => ['utc' => '+01:00', 'title_ru' => 'Африка/Касабланка'],
	'Africa/Ceuta' => ['utc' => '+01:00', 'title_ru' => 'Африка/Сеута'],
	'Africa/Conakry' => ['utc' => '+00:00', 'title_ru' => 'Африка/Конакри'],
	'Africa/Dakar' => ['utc' => '+00:00', 'title_ru' => 'Африка/Дакар'],
	'Africa/Dar_es_Salaam' => ['utc' => '+03:00', 'title_ru' => 'Африка/Дар-эс-Салам'],
	'Africa/Djibouti' => ['utc' => '+03:00', 'title_ru' => 'Африка/Джибути'],
	'Africa/Douala' => ['utc' => '+01:00', 'title_ru' => 'Африка/Дуала'],
	'Africa/El_Aaiun' => ['utc' => '+01:00', 'title_ru' => 'Африка/Эль-Аюн'],
	'Africa/Freetown' => ['utc' => '+00:00', 'title_ru' => 'Африка/Фритаун'],
	'Africa/Gaborone' => ['utc' => '+02:00', 'title_ru' => 'Африка/Габороне'],
	'Africa/Harare' => ['utc' => '+02:00', 'title_ru' => 'Африка/Хараре'],
	'Africa/Johannesburg' => ['utc' => '+02:00', 'title_ru' => 'Африка/Йоханнесбург'],
	'Africa/Juba' => ['utc' => '+03:00', 'title_ru' => 'Африка/Грива'],
	'Africa/Kampala' => ['utc' => '+03:00', 'title_ru' => 'Африка/Кампала'],
	'Africa/Khartoum' => ['utc' => '+02:00', 'title_ru' => 'Африка/Хартум'],
	'Africa/Kigali' => ['utc' => '+02:00', 'title_ru' => 'Африка/Кигали'],
	'Africa/Kinshasa' => ['utc' => '+01:00', 'title_ru' => 'Африка/Киншаса'],
	'Africa/Lagos' => ['utc' => '+01:00', 'title_ru' => 'Африка/Лагос'],
	'Africa/Libreville' => ['utc' => '+01:00', 'title_ru' => 'Африка/Либревиль'],
	'Africa/Lome' => ['utc' => '+00:00', 'title_ru' => 'Африка/Ломе'],
	'Africa/Luanda' => ['utc' => '+01:00', 'title_ru' => 'Африка/Луанда'],
	'Africa/Lubumbashi' => ['utc' => '+02:00', 'title_ru' => 'Африка/Лубумбаши'],
	'Africa/Lusaka' => ['utc' => '+02:00', 'title_ru' => 'Африка/Лусака'],
	'Africa/Malabo' => ['utc' => '+01:00', 'title_ru' => 'Африка/Малабо'],
	'Africa/Maputo' => ['utc' => '+02:00', 'title_ru' => 'Африка/Мапуту'],
	'Africa/Maseru' => ['utc' => '+02:00', 'title_ru' => 'Африка/Масеру'],
	'Africa/Mbabane' => ['utc' => '+02:00', 'title_ru' => 'Африка/Мбабане'],
	'Africa/Mogadishu' => ['utc' => '+03:00', 'title_ru' => 'Африка/Могадишо'],
	'Africa/Monrovia' => ['utc' => '+00:00', 'title_ru' => 'Африка/Монровия'],
	'Africa/Nairobi' => ['utc' => '+03:00', 'title_ru' => 'Африка/Найроби'],
	'Africa/Ndjamena' => ['utc' => '+01:00', 'title_ru' => 'Африка/Нджамена'],
	'Africa/Niamey' => ['utc' => '+01:00', 'title_ru' => 'Африка/Ниамей'],
	'Africa/Nouakchott' => ['utc' => '+00:00', 'title_ru' => 'Африка/Нуакшот'],
	'Africa/Ouagadougou' => ['utc' => '+00:00', 'title_ru' => 'Африка/Уагадугу'],
	'Africa/Porto-Novo' => ['utc' => '+01:00', 'title_ru' => 'Африка/Порто-Ново'],
	'Africa/Sao_Tome' => ['utc' => '+00:00', 'title_ru' => 'Африка/Святой Томас'],
	'Africa/Tripoli' => ['utc' => '+02:00', 'title_ru' => 'Африка/Триполи'],
	'Africa/Tunis' => ['utc' => '+01:00', 'title_ru' => 'Африка/Тунис'],
	'Africa/Windhoek' => ['utc' => '+02:00', 'title_ru' => 'Африка/Виндхук'],
	'America/Adak' => ['utc' => '-10:00', 'title_ru' => 'Америка/Адак'],
	'America/Anchorage' => ['utc' => '-09:00', 'title_ru' => 'Америка/Анкоридж'],
	'America/Anguilla' => ['utc' => '-04:00', 'title_ru' => 'Америка/Ангилья'],
	'America/Antigua' => ['utc' => '-04:00', 'title_ru' => 'Америка/Антигуа'],
	'America/Araguaina' => ['utc' => '-03:00', 'title_ru' => 'Америка/Арагуаина'],
	'America/Argentina/Buenos_Aires' => ['utc' => '-03:00', 'title_ru' => 'Америка/Аргентина'],
	'America/Argentina/Catamarca' => ['utc' => '-03:00', 'title_ru' => 'Америка/Аргентина'],
	'America/Argentina/Cordoba' => ['utc' => '-03:00', 'title_ru' => 'Америка/Аргентина'],
	'America/Argentina/Jujuy' => ['utc' => '-03:00', 'title_ru' => 'Америка/Аргентина'],
	'America/Argentina/La_Rioja' => ['utc' => '-03:00', 'title_ru' => 'Америка/Аргентина'],
	'America/Argentina/Mendoza' => ['utc' => '-03:00', 'title_ru' => 'Америка/Аргентина'],
	'America/Argentina/Rio_Gallegos' => ['utc' => '-03:00', 'title_ru' => 'Америка/Аргентина'],
	'America/Argentina/Salta' => ['utc' => '-03:00', 'title_ru' => 'Америка/Аргентина'],
	'America/Argentina/San_Juan' => ['utc' => '-03:00', 'title_ru' => 'Америка/Аргентина'],
	'America/Argentina/San_Luis' => ['utc' => '-03:00', 'title_ru' => 'Америка/Аргентина'],
	'America/Argentina/Tucuman' => ['utc' => '-03:00', 'title_ru' => 'Америка/Аргентина'],
	'America/Argentina/Ushuaia' => ['utc' => '-03:00', 'title_ru' => 'Америка/Аргентина'],
	'America/Aruba' => ['utc' => '-04:00', 'title_ru' => 'Америка/Аруба'],
	'America/Asuncion' => ['utc' => '-04:00', 'title_ru' => 'Америка/Асунсьон'],
	'America/Atikokan' => ['utc' => '-05:00', 'title_ru' => 'Америка/Атикокан'],
	'America/Bahia' => ['utc' => '-03:00', 'title_ru' => 'Америка/Бразилия'],
	'America/Bahia_Banderas' => ['utc' => '-06:00', 'title_ru' => 'Америка/Bahia Banderas'],
	'America/Barbados' => ['utc' => '-04:00', 'title_ru' => 'Америка/Барбадос'],
	'America/Belem' => ['utc' => '-03:00', 'title_ru' => 'Америка/Белен'],
	'America/Belize' => ['utc' => '-06:00', 'title_ru' => 'Америка/Белиз'],
	'America/Blanc-Sablon' => ['utc' => '-04:00', 'title_ru' => 'Америка/Blanc Sablon'],
	'America/Boa_Vista' => ['utc' => '-04:00', 'title_ru' => 'Америка/Хороший вид'],
	'America/Bogota' => ['utc' => '-05:00', 'title_ru' => 'Америка/Богота'],
	'America/Boise' => ['utc' => '-07:00', 'title_ru' => 'Америка/Бойсе'],
	'America/Cambridge_Bay' => ['utc' => '-07:00', 'title_ru' => 'Америка/Кембриджский залив'],
	'America/Campo_Grande' => ['utc' => '-04:00', 'title_ru' => 'Америка/Большое поле'],
	'America/Cancun' => ['utc' => '-05:00', 'title_ru' => 'Америка/Канкун'],
	'America/Caracas' => ['utc' => '-04:00', 'title_ru' => 'Америка/Каракас'],
	'America/Cayenne' => ['utc' => '-03:00', 'title_ru' => 'Америка/Cayenne'],
	'America/Cayman' => ['utc' => '-05:00', 'title_ru' => 'Америка/Кайман'],
	'America/Chicago' => ['utc' => '-06:00', 'title_ru' => 'Америка/Чикаго'],
	'America/Chihuahua' => ['utc' => '-07:00', 'title_ru' => 'Америка/Чихуахуа'],
	'America/Costa_Rica' => ['utc' => '-06:00', 'title_ru' => 'Америка/Коста-Рика'],
	'America/Creston' => ['utc' => '-07:00', 'title_ru' => 'Америка/Creston'],
	'America/Cuiaba' => ['utc' => '-04:00', 'title_ru' => 'Америка/Куяба'],
	'America/Curacao' => ['utc' => '-04:00', 'title_ru' => 'Америка/Кюрасао'],
	'America/Danmarkshavn' => ['utc' => '+00:00', 'title_ru' => 'Америка/Danmarkshavn'],
	'America/Dawson' => ['utc' => '-07:00', 'title_ru' => 'Америка/Доусон'],
	'America/Dawson_Creek' => ['utc' => '-07:00', 'title_ru' => 'Америка/Доусон Крик'],
	'America/Denver' => ['utc' => '-07:00', 'title_ru' => 'Америка/Денвер'],
	'America/Detroit' => ['utc' => '-05:00', 'title_ru' => 'Америка/Детройт'],
	'America/Dominica' => ['utc' => '-04:00', 'title_ru' => 'Америка/Доминика'],
	'America/Edmonton' => ['utc' => '-07:00', 'title_ru' => 'Америка/Эдмонтон'],
	'America/Eirunepe' => ['utc' => '-05:00', 'title_ru' => 'Америка/Эйрунепе'],
	'America/El_Salvador' => ['utc' => '-06:00', 'title_ru' => 'Америка/Эль Сальвадор'],
	'America/Fort_Nelson' => ['utc' => '-07:00', 'title_ru' => 'Америка/Форт Нельсон'],
	'America/Fortaleza' => ['utc' => '-03:00', 'title_ru' => 'Америка/Крепость'],
	'America/Glace_Bay' => ['utc' => '-04:00', 'title_ru' => 'Америка/Glace Bay'],
	'America/Godthab' => ['utc' => '-03:00', 'title_ru' => 'Америка/Годтаб'],
	'America/Goose_Bay' => ['utc' => '-04:00', 'title_ru' => 'Америка/Goose Bay'],
	'America/Grand_Turk' => ['utc' => '-05:00', 'title_ru' => 'Америка/Гранд-Терк'],
	'America/Grenada' => ['utc' => '-04:00', 'title_ru' => 'Америка/Гренада'],
	'America/Guadeloupe' => ['utc' => '-04:00', 'title_ru' => 'Америка/Гваделупа'],
	'America/Guatemala' => ['utc' => '-06:00', 'title_ru' => 'Америка/Гватемала'],
	'America/Guayaquil' => ['utc' => '-05:00', 'title_ru' => 'Америка/Гуаякиль'],
	'America/Guyana' => ['utc' => '-04:00', 'title_ru' => 'Америка/Гайана'],
	'America/Halifax' => ['utc' => '-04:00', 'title_ru' => 'Америка/Галифакс'],
	'America/Havana' => ['utc' => '-05:00', 'title_ru' => 'Америка/Гавана'],
	'America/Hermosillo' => ['utc' => '-07:00', 'title_ru' => 'Америка/Эрмосильо'],
	'America/Indiana/Indianapolis' => ['utc' => '-05:00', 'title_ru' => 'Америка/Индиана'],
	'America/Indiana/Knox' => ['utc' => '-06:00', 'title_ru' => 'Америка/Индиана'],
	'America/Indiana/Marengo' => ['utc' => '-05:00', 'title_ru' => 'Америка/Индиана'],
	'America/Indiana/Petersburg' => ['utc' => '-05:00', 'title_ru' => 'Америка/Индиана'],
	'America/Indiana/Tell_City' => ['utc' => '-06:00', 'title_ru' => 'Америка/Индиана'],
	'America/Indiana/Vevay' => ['utc' => '-05:00', 'title_ru' => 'Америка/Индиана'],
	'America/Indiana/Vincennes' => ['utc' => '-05:00', 'title_ru' => 'Америка/Индиана'],
	'America/Indiana/Winamac' => ['utc' => '-05:00', 'title_ru' => 'Америка/Индиана'],
	'America/Inuvik' => ['utc' => '-07:00', 'title_ru' => 'Америка/Инувик'],
	'America/Iqaluit' => ['utc' => '-05:00', 'title_ru' => 'Америка/Икалуит'],
	'America/Jamaica' => ['utc' => '-05:00', 'title_ru' => 'Америка/Ямайка'],
	'America/Juneau' => ['utc' => '-09:00', 'title_ru' => 'Америка/Джуно'],
	'America/Kentucky/Louisville' => ['utc' => '-05:00', 'title_ru' => 'Америка/Кентукки'],
	'America/Kentucky/Monticello' => ['utc' => '-05:00', 'title_ru' => 'Америка/Кентукки'],
	'America/Kralendijk' => ['utc' => '-04:00', 'title_ru' => 'Америка/Kralendijk'],
	'America/La_Paz' => ['utc' => '-04:00', 'title_ru' => 'Америка/Ла-Пас'],
	'America/Lima' => ['utc' => '-05:00', 'title_ru' => 'Америка/Лайм'],
	'America/Los_Angeles' => ['utc' => '-08:00', 'title_ru' => 'Америка/Лос-Анджелес'],
	'America/Lower_Princes' => ['utc' => '-04:00', 'title_ru' => 'Америка/Нижние князья'],
	'America/Maceio' => ['utc' => '-03:00', 'title_ru' => 'Америка/Масейо'],
	'America/Managua' => ['utc' => '-06:00', 'title_ru' => 'Америка/Манагуа'],
	'America/Manaus' => ['utc' => '-04:00', 'title_ru' => 'Америка/Манаус'],
	'America/Marigot' => ['utc' => '-04:00', 'title_ru' => 'Америка/Мариго'],
	'America/Martinique' => ['utc' => '-04:00', 'title_ru' => 'Америка/Мартиника'],
	'America/Matamoros' => ['utc' => '-06:00', 'title_ru' => 'Америка/Матаморос'],
	'America/Mazatlan' => ['utc' => '-07:00', 'title_ru' => 'Америка/Мазатлан'],
	'America/Menominee' => ['utc' => '-06:00', 'title_ru' => 'Америка/Menominee'],
	'America/Merida' => ['utc' => '-06:00', 'title_ru' => 'Америка/Мерида'],
	'America/Metlakatla' => ['utc' => '-09:00', 'title_ru' => 'Америка/Метлакатла'],
	'America/Mexico_City' => ['utc' => '-06:00', 'title_ru' => 'Америка/Мехико'],
	'America/Miquelon' => ['utc' => '-03:00', 'title_ru' => 'Америка/Микелон'],
	'America/Moncton' => ['utc' => '-04:00', 'title_ru' => 'Америка/Монктон'],
	'America/Monterrey' => ['utc' => '-06:00', 'title_ru' => 'Америка/Монтеррей'],
	'America/Montevideo' => ['utc' => '-03:00', 'title_ru' => 'Америка/Монтевидео'],
	'America/Montserrat' => ['utc' => '-04:00', 'title_ru' => 'Америка/Монсеррат'],
	'America/Nassau' => ['utc' => '-05:00', 'title_ru' => 'Америка/Нассау'],
	'America/New_York' => ['utc' => '-05:00', 'title_ru' => 'Америка/Нью-Йорк'],
	'America/Nipigon' => ['utc' => '-05:00', 'title_ru' => 'Америка/Нипигон'],
	'America/Nome' => ['utc' => '-09:00', 'title_ru' => 'Америка/имя'],
	'America/Noronha' => ['utc' => '-02:00', 'title_ru' => 'Америка/Noronha'],
	'America/North_Dakota/Beulah' => ['utc' => '-06:00', 'title_ru' => 'Америка/Северная Дакота'],
	'America/North_Dakota/Center' => ['utc' => '-06:00', 'title_ru' => 'Америка/Северная Дакота'],
	'America/North_Dakota/New_Salem' => ['utc' => '-06:00', 'title_ru' => 'Америка/Северная Дакота'],
	'America/Ojinaga' => ['utc' => '-07:00', 'title_ru' => 'Америка/Охинага'],
	'America/Panama' => ['utc' => '-05:00', 'title_ru' => 'Америка/Панама'],
	'America/Pangnirtung' => ['utc' => '-05:00', 'title_ru' => 'Америка/Пангниртунг'],
	'America/Paramaribo' => ['utc' => '-03:00', 'title_ru' => 'Америка/Парамарибо'],
	'America/Phoenix' => ['utc' => '-07:00', 'title_ru' => 'Америка/Феникс'],
	'America/Port-au-Prince' => ['utc' => '-05:00', 'title_ru' => 'Америка/Порт-о-Пренс'],
	'America/Port_of_Spain' => ['utc' => '-04:00', 'title_ru' => 'Америка/Порт-оф-Спейн'],
	'America/Porto_Velho' => ['utc' => '-04:00', 'title_ru' => 'Америка/Порту-Велью'],
	'America/Puerto_Rico' => ['utc' => '-04:00', 'title_ru' => 'Америка/Пуэрто-Рико'],
	'America/Punta_Arenas' => ['utc' => '-03:00', 'title_ru' => 'Америка/Пунта Аренас'],
	'America/Rainy_River' => ['utc' => '-06:00', 'title_ru' => 'Америка/Дождливая река'],
	'America/Rankin_Inlet' => ['utc' => '-06:00', 'title_ru' => 'Америка/Ранкин Инлет'],
	'America/Recife' => ['utc' => '-03:00', 'title_ru' => 'Америка/Ресифи'],
	'America/Regina' => ['utc' => '-06:00', 'title_ru' => 'Америка/Регина'],
	'America/Resolute' => ['utc' => '-06:00', 'title_ru' => 'Америка/Решительный'],
	'America/Rio_Branco' => ['utc' => '-05:00', 'title_ru' => 'Америка/Белая река'],
	'America/Santarem' => ['utc' => '-03:00', 'title_ru' => 'Америка/Сантарен'],
	'America/Santiago' => ['utc' => '-04:00', 'title_ru' => 'Америка/Сантьяго'],
	'America/Santo_Domingo' => ['utc' => '-04:00', 'title_ru' => 'Америка/Санто-Доминго'],
	'America/Sao_Paulo' => ['utc' => '-03:00', 'title_ru' => 'Америка/Сан-Паулу'],
	'America/Scoresbysund' => ['utc' => '-01:00', 'title_ru' => 'Америка/Scoresbysund'],
	'America/Sitka' => ['utc' => '-09:00', 'title_ru' => 'Америка/Ситка'],
	'America/St_Barthelemy' => ['utc' => '-04:00', 'title_ru' => 'Америка/Сен-Бартелеми'],
	'America/St_Johns' => ['utc' => '-03:30', 'title_ru' => 'Америка/Сент-Джонс'],
	'America/St_Kitts' => ['utc' => '-04:00', 'title_ru' => 'Америка/Сент-Китс'],
	'America/St_Lucia' => ['utc' => '-04:00', 'title_ru' => 'Америка/Сент-Люсия'],
	'America/St_Thomas' => ['utc' => '-04:00', 'title_ru' => 'Америка/Святой Томас'],
	'America/St_Vincent' => ['utc' => '-04:00', 'title_ru' => 'Америка/Сент-Винсент'],
	'America/Swift_Current' => ['utc' => '-06:00', 'title_ru' => 'Америка/Swift Current'],
	'America/Tegucigalpa' => ['utc' => '-06:00', 'title_ru' => 'Америка/Тегусигальпа'],
	'America/Thule' => ['utc' => '-04:00', 'title_ru' => 'Америка/Туле'],
	'America/Thunder_Bay' => ['utc' => '-05:00', 'title_ru' => 'Америка/Thunder Bay'],
	'America/Tijuana' => ['utc' => '-08:00', 'title_ru' => 'Америка/Тихуана'],
	'America/Toronto' => ['utc' => '-05:00', 'title_ru' => 'Америка/Торонто'],
	'America/Tortola' => ['utc' => '-04:00', 'title_ru' => 'Америка/Тортола'],
	'America/Vancouver' => ['utc' => '-08:00', 'title_ru' => 'Америка/Ванкувер'],
	'America/Whitehorse' => ['utc' => '-07:00', 'title_ru' => 'Америка/Белая лошадь'],
	'America/Winnipeg' => ['utc' => '-06:00', 'title_ru' => 'Америка/Виннипег'],
	'America/Yakutat' => ['utc' => '-09:00', 'title_ru' => 'Америка/Якутат'],
	'America/Yellowknife' => ['utc' => '-07:00', 'title_ru' => 'Америка/Йеллоунайф'],
	'Antarctica/Casey' => ['utc' => '+11:00', 'title_ru' => 'Антарктида/Кейси'],
	'Antarctica/Davis' => ['utc' => '+07:00', 'title_ru' => 'Антарктида/Дэвис'],
	'Antarctica/DumontDUrville' => ['utc' => '+10:00', 'title_ru' => 'Антарктида/DumontDUrville'],
	'Antarctica/Macquarie' => ['utc' => '+10:00', 'title_ru' => 'Антарктида/Macquarie'],
	'Antarctica/Mawson' => ['utc' => '+05:00', 'title_ru' => 'Антарктида/Моусон'],
	'Antarctica/McMurdo' => ['utc' => '+12:00', 'title_ru' => 'Антарктида/Макмердо'],
	'Antarctica/Palmer' => ['utc' => '-03:00', 'title_ru' => 'Антарктида/Палмер'],
	'Antarctica/Rothera' => ['utc' => '-03:00', 'title_ru' => 'Антарктида/Ротера'],
	'Antarctica/Syowa' => ['utc' => '+03:00', 'title_ru' => 'Антарктида/Syowa'],
	'Antarctica/Troll' => ['utc' => '+00:00', 'title_ru' => 'Антарктида/Тролль'],
	'Antarctica/Vostok' => ['utc' => '+06:00', 'title_ru' => 'Антарктида/Восток'],
	'Arctic/Longyearbyen' => ['utc' => '+01:00', 'title_ru' => 'Арктический/Longyearbyen'],
	'Asia/Aden' => ['utc' => '+03:00', 'title_ru' => 'Азия/Аден'],
	'Asia/Almaty' => ['utc' => '+06:00', 'title_ru' => 'Азия/Алматы'],
	'Asia/Amman' => ['utc' => '+02:00', 'title_ru' => 'Азия/Амман'],
	'Asia/Anadyr' => ['utc' => '+12:00', 'title_ru' => 'Азия/Анадырь'],
	'Asia/Aqtau' => ['utc' => '+05:00', 'title_ru' => 'Азия/Актау'],
	'Asia/Aqtobe' => ['utc' => '+05:00', 'title_ru' => 'Азия/Актобе'],
	'Asia/Ashgabat' => ['utc' => '+05:00', 'title_ru' => 'Азия/Ашхабад'],
	'Asia/Atyrau' => ['utc' => '+05:00', 'title_ru' => 'Азия/Атырау'],
	'Asia/Baghdad' => ['utc' => '+03:00', 'title_ru' => 'Азия/Багдад'],
	'Asia/Bahrain' => ['utc' => '+03:00', 'title_ru' => 'Азия/Бахрейн'],
	'Asia/Baku' => ['utc' => '+04:00', 'title_ru' => 'Азия/Баку'],
	'Asia/Bangkok' => ['utc' => '+07:00', 'title_ru' => 'Азия/Бангкок'],
	'Asia/Barnaul' => ['utc' => '+07:00', 'title_ru' => 'Азия/Барнаул'],
	'Asia/Beirut' => ['utc' => '+02:00', 'title_ru' => 'Азия/Бейрут'],
	'Asia/Bishkek' => ['utc' => '+06:00', 'title_ru' => 'Азия/Бишкек'],
	'Asia/Brunei' => ['utc' => '+08:00', 'title_ru' => 'Азия/Бруней'],
	'Asia/Chita' => ['utc' => '+09:00', 'title_ru' => 'Азия/Гепард'],
	'Asia/Choibalsan' => ['utc' => '+08:00', 'title_ru' => 'Азия/Чойбалсан'],
	'Asia/Colombo' => ['utc' => '+05:30', 'title_ru' => 'Азия/Коломбо'],
	'Asia/Damascus' => ['utc' => '+02:00', 'title_ru' => 'Азия/Дамаск'],
	'Asia/Dhaka' => ['utc' => '+06:00', 'title_ru' => 'Азия/Дакка'],
	'Asia/Dili' => ['utc' => '+09:00', 'title_ru' => 'Азия/Дили'],
	'Asia/Dubai' => ['utc' => '+04:00', 'title_ru' => 'Азия/Дубай'],
	'Asia/Dushanbe' => ['utc' => '+05:00', 'title_ru' => 'Азия/Душанбе'],
	'Asia/Famagusta' => ['utc' => '+02:00', 'title_ru' => 'Азия/Фамагуста'],
	'Asia/Gaza' => ['utc' => '+02:00', 'title_ru' => 'Азия/Газа'],
	'Asia/Hebron' => ['utc' => '+02:00', 'title_ru' => 'Азия/Хеврон'],
	'Asia/Ho_Chi_Minh' => ['utc' => '+07:00', 'title_ru' => 'Азия/Хо Ши Мин'],
	'Asia/Hong_Kong' => ['utc' => '+08:00', 'title_ru' => 'Азия/Гонконг'],
	'Asia/Hovd' => ['utc' => '+07:00', 'title_ru' => 'Азия/Ховд'],
	'Asia/Irkutsk' => ['utc' => '+08:00', 'title_ru' => 'Азия/Иркутск'],
	'Asia/Jakarta' => ['utc' => '+07:00', 'title_ru' => 'Азия/Джакарта'],
	'Asia/Jayapura' => ['utc' => '+09:00', 'title_ru' => 'Азия/Джаяпура'],
	'Asia/Jerusalem' => ['utc' => '+02:00', 'title_ru' => 'Азия/Иерусалим'],
	'Asia/Kabul' => ['utc' => '+04:30', 'title_ru' => 'Азия/Кабул'],
	'Asia/Kamchatka' => ['utc' => '+12:00', 'title_ru' => 'Азия/Камчатка'],
	'Asia/Karachi' => ['utc' => '+05:00', 'title_ru' => 'Азия/Карачи'],
	'Asia/Kathmandu' => ['utc' => '+05:45', 'title_ru' => 'Азия/Катманду'],
	'Asia/Khandyga' => ['utc' => '+09:00', 'title_ru' => 'Азия/Хандыга'],
	'Asia/Kolkata' => ['utc' => '+05:30', 'title_ru' => 'Азия/Калькутта'],
	'Asia/Krasnoyarsk' => ['utc' => '+07:00', 'title_ru' => 'Азия/Красноярск'],
	'Asia/Kuala_Lumpur' => ['utc' => '+08:00', 'title_ru' => 'Азия/Куала-Лумпур'],
	'Asia/Kuching' => ['utc' => '+08:00', 'title_ru' => 'Азия/Кучинг'],
	'Asia/Kuwait' => ['utc' => '+03:00', 'title_ru' => 'Азия/Кувейт'],
	'Asia/Macau' => ['utc' => '+08:00', 'title_ru' => 'Азия/Макао'],
	'Asia/Magadan' => ['utc' => '+11:00', 'title_ru' => 'Азия/Магадан'],
	'Asia/Makassar' => ['utc' => '+08:00', 'title_ru' => 'Азия/Макассар'],
	'Asia/Manila' => ['utc' => '+08:00', 'title_ru' => 'Азия/Манила'],
	'Asia/Muscat' => ['utc' => '+04:00', 'title_ru' => 'Азия/Маскат'],
	'Asia/Nicosia' => ['utc' => '+02:00', 'title_ru' => 'Азия/Никосия'],
	'Asia/Novokuznetsk' => ['utc' => '+07:00', 'title_ru' => 'Азия/Новокузнецк'],
	'Asia/Novosibirsk' => ['utc' => '+07:00', 'title_ru' => 'Азия/Новосибирск'],
	'Asia/Omsk' => ['utc' => '+06:00', 'title_ru' => 'Азия/Омск'],
	'Asia/Oral' => ['utc' => '+05:00', 'title_ru' => 'Азия/Устный'],
	'Asia/Phnom_Penh' => ['utc' => '+07:00', 'title_ru' => 'Азия/Пномпень'],
	'Asia/Pontianak' => ['utc' => '+07:00', 'title_ru' => 'Азия/Понтианак'],
	'Asia/Pyongyang' => ['utc' => '+09:00', 'title_ru' => 'Азия/Пхеньян'],
	'Asia/Qatar' => ['utc' => '+03:00', 'title_ru' => 'Азия/Катар'],
	'Asia/Qostanay' => ['utc' => '+06:00', 'title_ru' => 'Азия/Костанай'],
	'Asia/Qyzylorda' => ['utc' => '+05:00', 'title_ru' => 'Азия/Кызылорда'],
	'Asia/Riyadh' => ['utc' => '+03:00', 'title_ru' => 'Азия/Эр-Рияд'],
	'Asia/Sakhalin' => ['utc' => '+11:00', 'title_ru' => 'Азия/Сахалин'],
	'Asia/Samarkand' => ['utc' => '+05:00', 'title_ru' => 'Азия/Самарканд'],
	'Asia/Seoul' => ['utc' => '+09:00', 'title_ru' => 'Азия/Сеул'],
	'Asia/Shanghai' => ['utc' => '+08:00', 'title_ru' => 'Азия/Шанхай'],
	'Asia/Singapore' => ['utc' => '+08:00', 'title_ru' => 'Азия/Сингапур'],
	'Asia/Srednekolymsk' => ['utc' => '+11:00', 'title_ru' => 'Азия/Среднеколымск'],
	'Asia/Taipei' => ['utc' => '+08:00', 'title_ru' => 'Азия/Тайбэй'],
	'Asia/Tashkent' => ['utc' => '+05:00', 'title_ru' => 'Азия/Ташкент'],
	'Asia/Tbilisi' => ['utc' => '+04:00', 'title_ru' => 'Азия/Тбилиси'],
	'Asia/Tehran' => ['utc' => '+03:30', 'title_ru' => 'Азия/Тегеран'],
	'Asia/Thimphu' => ['utc' => '+06:00', 'title_ru' => 'Азия/Тхимпху'],
	'Asia/Tokyo' => ['utc' => '+09:00', 'title_ru' => 'Азия/Токио'],
	'Asia/Tomsk' => ['utc' => '+07:00', 'title_ru' => 'Азия/Томск'],
	'Asia/Ulaanbaatar' => ['utc' => '+08:00', 'title_ru' => 'Азия/Улан-Батор'],
	'Asia/Urumqi' => ['utc' => '+06:00', 'title_ru' => 'Азия/Урумчи'],
	'Asia/Ust-Nera' => ['utc' => '+10:00', 'title_ru' => 'Азия/Усть-Нера'],
	'Asia/Vientiane' => ['utc' => '+07:00', 'title_ru' => 'Азия/Вьентьян'],
	'Asia/Vladivostok' => ['utc' => '+10:00', 'title_ru' => 'Азия/Владивосток'],
	'Asia/Yakutsk' => ['utc' => '+09:00', 'title_ru' => 'Азия/Якутск'],
	'Asia/Yangon' => ['utc' => '+06:30', 'title_ru' => 'Азия/Янгон'],
	'Asia/Yekaterinburg' => ['utc' => '+05:00', 'title_ru' => 'Азия/Екатеринбург'],
	'Asia/Yerevan' => ['utc' => '+04:00', 'title_ru' => 'Азия/Ереван'],
	'Atlantic/Azores' => ['utc' => '-01:00', 'title_ru' => 'Атлантический/Азорские острова'],
	'Atlantic/Bermuda' => ['utc' => '-04:00', 'title_ru' => 'Атлантический/Бермуды'],
	'Atlantic/Canary' => ['utc' => '+00:00', 'title_ru' => 'Атлантический/Канарейка'],
	'Atlantic/Cape_Verde' => ['utc' => '-01:00', 'title_ru' => 'Атлантический/Кабо-Верде'],
	'Atlantic/Faroe' => ['utc' => '+00:00', 'title_ru' => 'Атлантический/Фарерские острова'],
	'Atlantic/Madeira' => ['utc' => '+00:00', 'title_ru' => 'Атлантический/дерево'],
	'Atlantic/Reykjavik' => ['utc' => '+00:00', 'title_ru' => 'Атлантический/Рейкьявик'],
	'Atlantic/South_Georgia' => ['utc' => '-02:00', 'title_ru' => 'Атлантический/Южная Георгия'],
	'Atlantic/St_Helena' => ['utc' => '+00:00', 'title_ru' => 'Атлантический/Святой Елены'],
	'Atlantic/Stanley' => ['utc' => '-03:00', 'title_ru' => 'Атлантический/Стэнли'],
	'Australia/Adelaide' => ['utc' => '+09:30', 'title_ru' => 'Австралия/Аделаида'],
	'Australia/Brisbane' => ['utc' => '+10:00', 'title_ru' => 'Австралия/Брисбен'],
	'Australia/Broken_Hill' => ['utc' => '+09:30', 'title_ru' => 'Австралия/Broken Hill'],
	'Australia/Currie' => ['utc' => '+10:00', 'title_ru' => 'Австралия/Карри'],
	'Australia/Darwin' => ['utc' => '+09:30', 'title_ru' => 'Австралия/Дарвин'],
	'Australia/Eucla' => ['utc' => '+08:45', 'title_ru' => 'Австралия/Евкла'],
	'Australia/Hobart' => ['utc' => '+10:00', 'title_ru' => 'Австралия/Хобарт'],
	'Australia/Lindeman' => ['utc' => '+10:00', 'title_ru' => 'Австралия/Lindeman'],
	'Australia/Lord_Howe' => ['utc' => '+10:30', 'title_ru' => 'Австралия/Лорд Хау'],
	'Australia/Melbourne' => ['utc' => '+10:00', 'title_ru' => 'Австралия/Мельбурн'],
	'Australia/Perth' => ['utc' => '+08:00', 'title_ru' => 'Австралия/Перт'],
	'Australia/Sydney' => ['utc' => '+10:00', 'title_ru' => 'Австралия/Сидней'],
	'Europe/Amsterdam' => ['utc' => '+01:00', 'title_ru' => 'Европа/Амстердам'],
	'Europe/Andorra' => ['utc' => '+01:00', 'title_ru' => 'Европа/Андорра'],
	'Europe/Astrakhan' => ['utc' => '+04:00', 'title_ru' => 'Европа/Астрахань'],
	'Europe/Athens' => ['utc' => '+02:00', 'title_ru' => 'Европа/Афины'],
	'Europe/Belgrade' => ['utc' => '+01:00', 'title_ru' => 'Европа/Белград'],
	'Europe/Berlin' => ['utc' => '+01:00', 'title_ru' => 'Европа/Берлин'],
	'Europe/Bratislava' => ['utc' => '+01:00', 'title_ru' => 'Европа/Братислава'],
	'Europe/Brussels' => ['utc' => '+01:00', 'title_ru' => 'Европа/Брюссель'],
	'Europe/Bucharest' => ['utc' => '+02:00', 'title_ru' => 'Европа/Бухарест'],
	'Europe/Budapest' => ['utc' => '+01:00', 'title_ru' => 'Европа/Будапешт'],
	'Europe/Busingen' => ['utc' => '+01:00', 'title_ru' => 'Европа/Бусинген'],
	'Europe/Chisinau' => ['utc' => '+02:00', 'title_ru' => 'Европа/Кишинэу'],
	'Europe/Copenhagen' => ['utc' => '+01:00', 'title_ru' => 'Европа/Копенгаген'],
	'Europe/Dublin' => ['utc' => '+01:00', 'title_ru' => 'Европа/Дублин'],
	'Europe/Gibraltar' => ['utc' => '+01:00', 'title_ru' => 'Европа/Гибралтар'],
	'Europe/Guernsey' => ['utc' => '+00:00', 'title_ru' => 'Европа/Гернси'],
	'Europe/Helsinki' => ['utc' => '+02:00', 'title_ru' => 'Европа/Хельсинки'],
	'Europe/Isle_of_Man' => ['utc' => '+00:00', 'title_ru' => 'Европа/Остров Мэн'],
	'Europe/Istanbul' => ['utc' => '+03:00', 'title_ru' => 'Европа/Стамбул'],
	'Europe/Jersey' => ['utc' => '+00:00', 'title_ru' => 'Европа/Джерси'],
	'Europe/Kaliningrad' => ['utc' => '+02:00', 'title_ru' => 'Европа/Калининград'],
	'Europe/Kiev' => ['utc' => '+02:00', 'title_ru' => 'Европа/Киев'],
	'Europe/Kirov' => ['utc' => '+03:00', 'title_ru' => 'Европа/Киров'],
	'Europe/Lisbon' => ['utc' => '+00:00', 'title_ru' => 'Европа/Лиссабон'],
	'Europe/Ljubljana' => ['utc' => '+01:00', 'title_ru' => 'Европа/Любляна'],
	'Europe/London' => ['utc' => '+00:00', 'title_ru' => 'Европа/Лондон'],
	'Europe/Luxembourg' => ['utc' => '+01:00', 'title_ru' => 'Европа/Люксембург'],
	'Europe/Madrid' => ['utc' => '+01:00', 'title_ru' => 'Европа/Мадрид'],
	'Europe/Malta' => ['utc' => '+01:00', 'title_ru' => 'Европа/Мальта'],
	'Europe/Mariehamn' => ['utc' => '+02:00', 'title_ru' => 'Европа/Мариехамн'],
	'Europe/Minsk' => ['utc' => '+03:00', 'title_ru' => 'Европа/Минске'],
	'Europe/Monaco' => ['utc' => '+01:00', 'title_ru' => 'Европа/Монако'],
	'Europe/Moscow' => ['utc' => '+03:00', 'title_ru' => 'Европа/Москва'],
	'Europe/Oslo' => ['utc' => '+01:00', 'title_ru' => 'Европа/Осло'],
	'Europe/Paris' => ['utc' => '+01:00', 'title_ru' => 'Европа/Париж'],
	'Europe/Podgorica' => ['utc' => '+01:00', 'title_ru' => 'Европа/Подгорица'],
	'Europe/Prague' => ['utc' => '+01:00', 'title_ru' => 'Европа/Прага'],
	'Europe/Riga' => ['utc' => '+02:00', 'title_ru' => 'Европа/Рига'],
	'Europe/Rome' => ['utc' => '+01:00', 'title_ru' => 'Европа/Рим'],
	'Europe/Samara' => ['utc' => '+04:00', 'title_ru' => 'Европа/Самара'],
	'Europe/San_Marino' => ['utc' => '+01:00', 'title_ru' => 'Европа/Сан-Марино'],
	'Europe/Sarajevo' => ['utc' => '+01:00', 'title_ru' => 'Европа/Сараево'],
	'Europe/Saratov' => ['utc' => '+04:00', 'title_ru' => 'Европа/Саратов'],
	'Europe/Simferopol' => ['utc' => '+03:00', 'title_ru' => 'Европа/Симферополь'],
	'Europe/Skopje' => ['utc' => '+01:00', 'title_ru' => 'Европа/Скопье'],
	'Europe/Sofia' => ['utc' => '+02:00', 'title_ru' => 'Европа/София'],
	'Europe/Stockholm' => ['utc' => '+01:00', 'title_ru' => 'Европа/Стокгольм'],
	'Europe/Tallinn' => ['utc' => '+02:00', 'title_ru' => 'Европа/Таллинн'],
	'Europe/Tirane' => ['utc' => '+01:00', 'title_ru' => 'Европа/Тиран'],
	'Europe/Ulyanovsk' => ['utc' => '+04:00', 'title_ru' => 'Европа/Ульяновск'],
	'Europe/Uzhgorod' => ['utc' => '+02:00', 'title_ru' => 'Европа/Ужгород'],
	'Europe/Vaduz' => ['utc' => '+01:00', 'title_ru' => 'Европа/Вадуц'],
	'Europe/Vatican' => ['utc' => '+01:00', 'title_ru' => 'Европа/Ватикан'],
	'Europe/Vienna' => ['utc' => '+01:00', 'title_ru' => 'Европа/Вена'],
	'Europe/Vilnius' => ['utc' => '+02:00', 'title_ru' => 'Европа/Вильнюс'],
	'Europe/Volgograd' => ['utc' => '+03:00', 'title_ru' => 'Европа/Волгоград'],
	'Europe/Warsaw' => ['utc' => '+01:00', 'title_ru' => 'Европа/Варшава'],
	'Europe/Zagreb' => ['utc' => '+01:00', 'title_ru' => 'Европа/Загреб'],
	'Europe/Zaporozhye' => ['utc' => '+02:00', 'title_ru' => 'Европа/Запорожье'],
	'Europe/Zurich' => ['utc' => '+01:00', 'title_ru' => 'Европа/Цюрих'],
	'Indian/Antananarivo' => ['utc' => '+03:00', 'title_ru' => 'Индийский/Антананариву'],
	'Indian/Chagos' => ['utc' => '+06:00', 'title_ru' => 'Индийский/Чагос'],
	'Indian/Christmas' => ['utc' => '+07:00', 'title_ru' => 'Индийский/Рождество'],
	'Indian/Cocos' => ['utc' => '+06:30', 'title_ru' => 'Индийский/Кокосы'],
	'Indian/Comoro' => ['utc' => '+03:00', 'title_ru' => 'Индийский/Коморо'],
	'Indian/Kerguelen' => ['utc' => '+05:00', 'title_ru' => 'Индийский/Кергелен'],
	'Indian/Mahe' => ['utc' => '+04:00', 'title_ru' => 'Индийский/Маэ'],
	'Indian/Maldives' => ['utc' => '+05:00', 'title_ru' => 'Индийский/Мальдивы'],
	'Indian/Mauritius' => ['utc' => '+04:00', 'title_ru' => 'Индийский/Маврикий'],
	'Indian/Mayotte' => ['utc' => '+03:00', 'title_ru' => 'Индийский/Майотта'],
	'Indian/Reunion' => ['utc' => '+04:00', 'title_ru' => 'Индийский/Воссоединение'],
	'Pacific/Apia' => ['utc' => '+13:00', 'title_ru' => 'Тихий океан/Умывальник'],
	'Pacific/Auckland' => ['utc' => '+12:00', 'title_ru' => 'Тихий океан/Окленд'],
	'Pacific/Bougainville' => ['utc' => '+11:00', 'title_ru' => 'Тихий океан/Бугенвиль'],
	'Pacific/Chatham' => ['utc' => '+12:45', 'title_ru' => 'Тихий океан/Chatham'],
	'Pacific/Chuuk' => ['utc' => '+10:00', 'title_ru' => 'Тихий океан/Чуук'],
	'Pacific/Easter' => ['utc' => '-06:00', 'title_ru' => 'Тихий океан/Пасха'],
	'Pacific/Efate' => ['utc' => '+11:00', 'title_ru' => 'Тихий океан/Эфате'],
	'Pacific/Enderbury' => ['utc' => '+13:00', 'title_ru' => 'Тихий океан/Эндербери'],
	'Pacific/Fakaofo' => ['utc' => '+13:00', 'title_ru' => 'Тихий океан/Факаофо'],
	'Pacific/Fiji' => ['utc' => '+12:00', 'title_ru' => 'Тихий океан/Фиджи'],
	'Pacific/Funafuti' => ['utc' => '+12:00', 'title_ru' => 'Тихий океан/Фунафути'],
	'Pacific/Galapagos' => ['utc' => '-06:00', 'title_ru' => 'Тихий океан/Галапагосские острова'],
	'Pacific/Gambier' => ['utc' => '-09:00', 'title_ru' => 'Тихий океан/Гамбье'],
	'Pacific/Guadalcanal' => ['utc' => '+11:00', 'title_ru' => 'Тихий океан/Гуадалканал'],
	'Pacific/Guam' => ['utc' => '+10:00', 'title_ru' => 'Тихий океан/Гуам'],
	'Pacific/Honolulu' => ['utc' => '-10:00', 'title_ru' => 'Тихий океан/Гонолулу'],
	'Pacific/Kiritimati' => ['utc' => '+14:00', 'title_ru' => 'Тихий океан/Киритимати'],
	'Pacific/Kosrae' => ['utc' => '+11:00', 'title_ru' => 'Тихий океан/Kosrae'],
	'Pacific/Kwajalein' => ['utc' => '+12:00', 'title_ru' => 'Тихий океан/Кваджалейн'],
	'Pacific/Majuro' => ['utc' => '+12:00', 'title_ru' => 'Тихий океан/Маджуро'],
	'Pacific/Marquesas' => ['utc' => '-09:30', 'title_ru' => 'Тихий океан/Маркизские острова'],
	'Pacific/Midway' => ['utc' => '-11:00', 'title_ru' => 'Тихий океан/Мидуэй'],
	'Pacific/Nauru' => ['utc' => '+12:00', 'title_ru' => 'Тихий океан/Науру'],
	'Pacific/Niue' => ['utc' => '-11:00', 'title_ru' => 'Тихий океан/Ниуэ'],
	'Pacific/Norfolk' => ['utc' => '+11:00', 'title_ru' => 'Тихий океан/Норфолк'],
	'Pacific/Noumea' => ['utc' => '+11:00', 'title_ru' => 'Тихий океан/Нумеа'],
	'Pacific/Pago_Pago' => ['utc' => '-11:00', 'title_ru' => 'Тихий океан/Платный Платный'],
	'Pacific/Palau' => ['utc' => '+09:00', 'title_ru' => 'Тихий океан/Палау'],
	'Pacific/Pitcairn' => ['utc' => '-08:00', 'title_ru' => 'Тихий океан/Питкэрн'],
	'Pacific/Pohnpei' => ['utc' => '+11:00', 'title_ru' => 'Тихий океан/Понпеи'],
	'Pacific/Port_Moresby' => ['utc' => '+10:00', 'title_ru' => 'Тихий океан/Порт-Морсби'],
	'Pacific/Rarotonga' => ['utc' => '-10:00', 'title_ru' => 'Тихий океан/Раротонга'],
	'Pacific/Saipan' => ['utc' => '+10:00', 'title_ru' => 'Тихий океан/Сайпан'],
	'Pacific/Tahiti' => ['utc' => '-10:00', 'title_ru' => 'Тихий океан/Таити'],
	'Pacific/Tarawa' => ['utc' => '+12:00', 'title_ru' => 'Тихий океан/Тарава'],
	'Pacific/Tongatapu' => ['utc' => '+13:00', 'title_ru' => 'Тихий океан/Тонгатапу'],
	'Pacific/Wake' => ['utc' => '+12:00', 'title_ru' => 'Тихий океан/Проснуться'],
	'Pacific/Wallis' => ['utc' => '+12:00', 'title_ru' => 'Тихий океан/Уоллис'],
	'UTC' => ['utc' => '+00:00', 'title_ru' => 'Всемирное координированное время'],
];

print_r($timezones);
